apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: node-exporter

commonLabels:
  app: node-exporter

resources:
- namespace.yml
- service-account.yml
- clusterrolebinding.yml
- daemonset.yml
